server:
  port: 8080

spring:
  profiles:
    include: secret # ??? oauth2.0 ??? ??. ? ??? application-secret.yml? ??

  datasource:
    h2:
      url: jdbc:h2:mem:3659a7f0-3dde-405e-8d1b-0be160a0c52d
      username: sa
      password:
      driver-class-name: org.h2.Driver

    mysql:
      url: jdbc:mysql://salon.cxua2wwkqvhz.ap-northeast-2.rds.amazonaws.com:3306/salon
      username: root
      password: salon1234!
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # ?? ??? ???? none?? ?? ??.
    show-sql: true  # ???? ?? ??.
    properties:
      hibernate:
        format_sql: true # ??? ?? ?? ???.